/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transporte;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CARLOS ALEJANDRO
 */
public class Solucion extends javax.swing.JFrame {

    MetodoDelTransporte met=new MetodoDelTransporte();
    DefaultTableModel origenModel;
    DefaultTableModel destinoModel;
    DatosPrueba datos=new DatosPrueba();
    /**
     * Creates new form JFrameTransporte
     */
    public Solucion() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TPSolucion = new javax.swing.JTabbedPane();
        PSolucion = new javax.swing.JPanel();
        spSolucion = new javax.swing.JScrollPane();
        tbSolucion = new javax.swing.JTable();
        POptimo = new javax.swing.JPanel();
        spOptimo = new javax.swing.JScrollPane();
        tbOptimo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblCostoMinimo = new javax.swing.JLabel();
        PProceso = new javax.swing.JPanel();
        spProceso = new javax.swing.JScrollPane();
        txtProceso = new javax.swing.JTextArea();
        lblESD = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mINuevo = new javax.swing.JMenuItem();
        mIGuardar = new javax.swing.JMenuItem();
        mIGuardarComo = new javax.swing.JMenuItem();
        mISalir = new javax.swing.JMenuItem();
        mEditar = new javax.swing.JMenu();
        mIEditCosto = new javax.swing.JMenuItem();
        mIEditDemanda = new javax.swing.JMenuItem();
        mIEditOferta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método del Transporte");

        TPSolucion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tbSolucion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbSolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spSolucion.setViewportView(tbSolucion);

        javax.swing.GroupLayout PSolucionLayout = new javax.swing.GroupLayout(PSolucion);
        PSolucion.setLayout(PSolucionLayout);
        PSolucionLayout.setHorizontalGroup(
            PSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spSolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
        PSolucionLayout.setVerticalGroup(
            PSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spSolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        TPSolucion.addTab("Tabla Solucion", PSolucion);

        tbOptimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spOptimo.setViewportView(tbOptimo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Costo Mínimo:");

        lblCostoMinimo.setBackground(new java.awt.Color(255, 102, 51));
        lblCostoMinimo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCostoMinimo.setForeground(new java.awt.Color(255, 102, 51));
        lblCostoMinimo.setText(" ");

        javax.swing.GroupLayout POptimoLayout = new javax.swing.GroupLayout(POptimo);
        POptimo.setLayout(POptimoLayout);
        POptimoLayout.setHorizontalGroup(
            POptimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POptimoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spOptimo, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(POptimoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCostoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        POptimoLayout.setVerticalGroup(
            POptimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POptimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(POptimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCostoMinimo))
                .addGap(17, 17, 17)
                .addComponent(spOptimo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TPSolucion.addTab("Tabla Distribución Optíma", POptimo);

        txtProceso.setColumns(20);
        txtProceso.setRows(5);
        spProceso.setViewportView(txtProceso);

        javax.swing.GroupLayout PProcesoLayout = new javax.swing.GroupLayout(PProceso);
        PProceso.setLayout(PProcesoLayout);
        PProcesoLayout.setHorizontalGroup(
            PProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PProcesoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
        PProcesoLayout.setVerticalGroup(
            PProcesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PProcesoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        TPSolucion.addTab("Proceso", PProceso);

        lblESD.setText("ESD115 - 2017 - Programación Lineal");

        Menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mArchivo.setText("Archivo");
        mArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mINuevo.setText("Nuevo");
        mArchivo.add(mINuevo);

        mIGuardar.setText("Guardar...");
        mArchivo.add(mIGuardar);

        mIGuardarComo.setText("Guardar como...");
        mArchivo.add(mIGuardarComo);

        mISalir.setText("Salir");
        mArchivo.add(mISalir);

        Menu.add(mArchivo);

        mEditar.setText("Editar");
        mEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mIEditCosto.setText("Editar Costos");
        mEditar.add(mIEditCosto);

        mIEditDemanda.setText("Editar Demanda");
        mEditar.add(mIEditDemanda);

        mIEditOferta.setText("Editar Oferta");
        mEditar.add(mIEditOferta);

        Menu.add(mEditar);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPSolucion)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblESD)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPSolucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblESD)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel POptimo;
    private javax.swing.JPanel PProceso;
    private javax.swing.JPanel PSolucion;
    private javax.swing.JTabbedPane TPSolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCostoMinimo;
    private javax.swing.JLabel lblESD;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mEditar;
    private javax.swing.JMenuItem mIEditCosto;
    private javax.swing.JMenuItem mIEditDemanda;
    private javax.swing.JMenuItem mIEditOferta;
    private javax.swing.JMenuItem mIGuardar;
    private javax.swing.JMenuItem mIGuardarComo;
    private javax.swing.JMenuItem mINuevo;
    private javax.swing.JMenuItem mISalir;
    private javax.swing.JScrollPane spOptimo;
    private javax.swing.JScrollPane spProceso;
    private javax.swing.JScrollPane spSolucion;
    private javax.swing.JTable tbOptimo;
    private javax.swing.JTable tbSolucion;
    private javax.swing.JTextArea txtProceso;
    // End of variables declaration//GEN-END:variables
}
